-- Populate Courses table
insert into COURSE (cno, cname, credits, dno) values ('COMP1000', 'Media Computing', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1005', 'An Introduction to Programming for Data Science', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1010', 'Computing I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1020', 'Computing II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1030L', 'Computing I Lab', 1, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1040L', 'Computing II Lab', 1, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1080', 'Intro to App Des & Mobile Comp', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1120', 'Undeclared Science Seminar', 1, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1130', 'Exploring the Internet', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP1500', 'Topics in Computer Science', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2010', 'Computing III', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2010L', 'Computing III Lab', 1, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2030', 'Assembly Language Programming', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2030L', 'Assembly Language Programming Lab', 1, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2040', 'Computing IV', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2110', 'Computer Science for SRT Applications', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP2120', 'Special Topics: Sound Thinking', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3010', 'Organization of Progamming Languages', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3040', 'Foundations of Computer Science', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3050', 'Computer Architecture', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3080', 'Operating Systems', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3090', 'Database I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3100', 'Database II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3500', 'Special Topics', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP3611', 'Introduction to Computer Security', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4010', 'Sofware Project I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4020', 'Sofware Project II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4040', 'Analysis of Algorithms', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4050', 'Parallel Processing', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4060', 'Compiler Construction I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4110', 'Sofware Engineering I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4110', 'Sofware Engineering II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4130', 'Data Communications I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4140', 'Data Communications II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4200', 'Artificial Intelligence', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4210', 'Data Mining', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4220', 'Machine Learning', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4230', 'Computer Vision I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4270', 'Computer Graphics I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4280', 'Computer Graphics II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4290', 'Bioinformatics for CS', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4420', 'Natural Language Processing', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4500', 'Mobile Robotics I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4510', 'Mobile Robotics II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4570', 'Computer Security', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4600', 'Selected Topics', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4610', 'Graphical User Interface Programming I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4611', 'Cyber Crime Investigation', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4620', 'Graphical User Interface Programming II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4630', 'Mobile App Programming I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4631', 'Mobile App Programming II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4800', 'Honors Project I', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4810', 'Honors Project II', 3, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4900', 'Directed Studies in Computer Science', 4, 1);
insert into COURSE (cno, cname, credits, dno) values ('COMP4930', 'Cooperative Education in Computer Science', 1, 1);




-- Populate courses prerequisites table
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP1020', 'COMP1010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP2010', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP2030', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP2040', 'COMP2010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3040', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3050', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3050', 'COMP2030');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3080', 'COMP3050');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3090', 'COMP2040');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3100', 'COMP3090');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP3500', 'COMP3050');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4040', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4050', 'COMP3080');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4110', 'COMP2040');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4120', 'COMP4120');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4130', 'COMP3080');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4140', 'COMP4130');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4200', 'COMP3010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4130', 'COMP3080');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4210', 'COMP4200');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4220', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4230', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4270', 'COMP2010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4280', 'COMP4270');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4290', 'COMP2010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4420', 'COMP4220');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4500', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4510', 'COMP1020');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4570', 'COMP4130');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4570', 'COMP4040');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4610', 'COMP2010');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4611', 'COMP4130');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4620', 'COMP4610');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4630', 'COMP2040');
insert into COURSE_PREREQUISITE (cno, prerequisite_cno) values ('COMP4631', 'COMP4630');
